language: java
notifications:
  slack:
    secure: XLVjxHQAEWnyFMtrmvbh1rf/OPrZTVou6g8q5LXkt0FLCo91VAhZ5LxkqlsvfCE4Ay0suoIYopFug1O6o7+2yIMMsFKOLfwnmO4KYq3HB3yb5kWkUCi4nTuK7pfKV8/7su9FZ0OdRnCg/kHYnzyXRKS80yuKJ+CNcwDI9J4wfG5uuWgPl+Z8A877X4a+J8nk0IfWpn0wumZC+eQ+BLxLpM1xbCh7Q9j7Nd4slYGnWFHj/IeCWFkkBWBlXwQK1yExKU1bAvrLfnZhJmxaqJdMO2IMQVVptHV+Hq7L/VeC6M9fV9o7crAAW37dsayiEntK/DwmXI303LZpXkgJ6H2iA9tH3r60zJjFDPuOTaCKPO+/CxpbkjHSjR6+KdKQsvBzxiNl1M45yfMamyBpoerR1wbAMoFUc2TGflxOWgbEATKAehfxVMEnbvBeP+xGUX+pC2LODYvoMIr+bnXxTtfAM4kYxCvu1MJHnhzjaNeQXN696/GiTKKnYVYIkFsNzmU6OSxZjavF/WfOWZiifE2sZ7H/jVqxk9AcND4cRyfOPg7KHpARUwVmi8/ehtLcObTKiIH56sOpin2ybU37UINNVFRZKknojhfoesi8erv/FPvO9zQ2arIidqcrNQFLnGbGnCsJkMlk8AJYd6az6XcqJHGtgaO1gg6oCfzGYiFgxP4=
deploy:
  provider: releases
  api_key:
    secure: eI2FTYaWJjtvZximjYMsVzpj48mi2NEB2QyANpOzD/T+6MBfoQpAqg1KLjjqZydt3B+9nN79hapzRfeocbiVIlynsLM1dNXHuLC91yNW+4j1hXIJyPd8q1GqvVspEIO19Oit5GvPTxu3s5XlGjByizZuii8zLgmSRJb+nVqnD+llHFpiFMDtVT/QFTeqIypXX0te051UHtdAjGraPgYjs5OhEFPB8v1rg5nrVyj/Tbop7t2lL6Hg0r/PNlM9tIFEelX6tcrD1MTnnPUIvq1s7jIC1cm8OKgroL7sEE2C57q6N64jRwnl2qFy3xEys9QuI+R+B5V1wU9HHsGcqMkxu1dBARsKS1vN3YZ/YFDz7uFhe+CchnUNCSAIYTKxoKTTE9bsaJ3a/G4n0D1hYiKccK0rqaAs5QqsRJ34i+DnMFJcQzMPSc43JlUfQ0Up5qIYHtD4/WnP9Be7+upKKOlIROdfBBKWX2Z1FG08QL/y8TVCez9tq2dHYvC0tleFwpDf25T/Tcp5AxBDDUkF1+vzVWuRzpAn9t6FEBaKEK4pOzZI72nGR6m+1rv7PB6PA1bQlhARN5AdA8pcepXYh1oWuLPd7gQOcVLsEAK70vrGBMFsSCcKp/zSjCTGRcAoDvxEps7ZIkduf0qXQ8XP2mRFLY6pFJ56cHM2vBPvCcG4mZg=
  file: build/libs/xlr-qtest-plugin-1.1.1.jar
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: xebialabs-community/xlr-qtest-plugin
