language: java
notifications:
  hipchat:
    rooms:
      secure: CD77cohawdMYwZXvL6b8At0d43fSYW5/9K17UjJsKz2LR2Wf2GZiYDiCGydxq4KQ/S4dKzSB7yfac4MXrzKdwiDnQYokfiHqMr6qtvzqXXpCEViz6dImOR4yYbrp3VfaY6nXgYYjMaF5dQ6Wsca42zgnpd3ZNi8/Ylo2x4gsUhGKtqidGnCVmo3NB1J6QHJk6cRvsQmy9p2ZroSrLpQWAGRN3OyiiduoKvCPrhk5OTwuuJbhR4ECwtOfWnBRtpMTWauOex7z7Qn2vLQbZ+DIspQxjoA1Pb6Qm4TGG8G1DBWb9rDjFjDV4DhBI/dTpS1Ov7cRNLiop1aFtQEbkwcAurypCAlkvqvUpU444VUMhmaAWFXTqOKWKDVbBR0DogsLW6wE43QhHpNByahb6vUOfpdqfcAWoDCaoPbR7RmrP34XMYVnb/PIFg8h1H4HNEqTF4ixFPqcWhUfMZW2ADjIIHGI25/Ylt68GA50On4/oXdNp1wE+qsR/nJKGT8EM2BhYolXDoPJtMsDdxWaAnoGR9evOEAXUsH6PMfCIYjOk78kVyRsUt2evIdrUK8MFe8yYy9T53Wq+YFfIGeTVqXEMhAiDzzb9jU55ixjDMgl0ITLX03VjpPtxGLWd31e05+KA9AP47P2Bv/cQsCluWxHqWZ1MRfogo7tz1v5qqOHrDQ=
deploy:
  provider: releases
  api_key:
    secure: iNDRtQ9F95+3c8+znu2UF1FK7LPM4LI+VWmJR4XTl+fND20lchf9qkdD3C2zL0+RLOYt8sKrykcVkebDx+z6j2rNvCj8ZTYiHrgn2xPilTHZUOSqAHc/Kqx+LgewTka1x8qx7VYGAoChUvU0t61VRy/izjGGMkQhKWq2zj3mu+JhiJo753mK3faiA2/593LnrlvnbQy44fG7oZVxRwPQxdiqoUGY+Pz3EMYxZFGm8q1s7Aiv3JAxbwqenJKOMMTYRGtmRaYIFOHxow2PJAfk6wZsgVX1jqJmmQ5G/43h9eaWJg+E+XYb4erfbD8cHQJ0BKZmK6x6TcWKLK5jNLAYeRpJk8l05nzkfEEWjiABF9oLDS7wGhWC/EzfMIlCLtu5W0dpGta0AOAFRQNiS0UDfOEh/o8a3HmA4IQqNH9woaMbqnKS1r+dHVk18042r9Ne+eU7PdrUIEM9+AjJRLCvrZrvb/Lp6hLM6bkiDxwhhnR0iz6wN2Xc5k0h406U2zVlDrvsMSWFdgdKjSEO/gnYwANsnCNN1gaN2oNlS+JFg9v931ccN1rpKsE3fdD/MtkkT2WGINoMAX0NwdFnh2C8yILv+lpgRcmRTlio412BNrBJTZofazdeSN+hJqlO+aMoBGZTGvN+dLhjHmsYBBiiMvvqZZIaHPfH43g9Z9atKEA=
  file: build/libs/xlr-qtest-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-qtest-plugin
