language: java
notifications:
  hipchat:
    rooms:
      secure: LqWr/QVOl4HRIlJb2ZgJefh/uK6hFRJGba8Z0SlGdNyZ2oWrLOVtLL7dPnG3XcFNuErEM32GowPiHm+ParzRvAs3aouF6c++gpSysYME4PlcwCXbrwqe2S+PbrNLXChzIlb4zqQAYww+QU/pgQqZjU175nR98WmdLBzVH5sG744oPL0LGhd44ikBHKZ+Atkm7+7If8RPYgWSGg9lcQRtmVeONer4W1NJIdXj+2ZMGeXM7Rf/7HuwutuTnZSbz3aIvoQflDD4HXtFPuYIYHfcH9wTMcI/W1QePcYhlGmwn9Y6wKxZKf0dH8n0vCwra0Zo9eZZ/q8DygXUNxfRmwGe36efei6DZJ9BqSnAjQrfcBVBu0tlnwp+i7/RFNnRgjDOzboDzuSuju2Fd8HVxE67ML7YUEFzFpRxk29poQT9B8DCoDt2xvyTKPOrucF6VMKAQRLyqrH+9rYRejvZQKRGyOByEQmZhf425ZdzaHLy//lhW7xaGDU9RSb3+oUFO9GcpDNbsHvkNmidHFd3T7VofNzbBeq6Pd50jFYl9zTYKMiBWHAnV3cxgi/mYZ/AF8VbAw7bOOIsGAlqBwH1EO/5vSuUbWVoAPj8so+9v8f62lcb/uNJesUDQW/gzFZTfHj8PUEd8ZPz3OZaxvIBqPYoYzxwpnLuzf9Zs9LXQZQW7h0=
    on_success: always
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: LiAHufqUbsV6Qv0XWwiDx90wDXsbf4+36I349/wx91d2hSZBgkaqPgDdLwLXPIP9ViXOx/agkV/C9Dmm3jPQSSczCwlFGoKfrWLKyEnOrVDnZnNa/EtZi+odAplfBO4sB+m9KAng0X5NWU+qeXB4mFD5+uI9gi5GJfhDoAcpu7yVKJt6Ukyf/ars3P52bfCqVN0ockwC3GcUCsJM5uFM71TPmFK5G4ir+C7Z3GEtAezJqCuNitnK6e0PMIwdnnH0cEV2xNyjKV5ikPs8/GgI/oXKSSVWQAoL+948XSeUNqBQNInrXA/6anskN07+4QIW65WL5KA3dLyZzkerhi1SD/W5AVl/2BupYu/sw8zEH0ffyLK6Tq5SIb34N4MtVy805FslYpnMGYH+1rZDq2vBMmGK3mhCxyuyLaC5eLfc7KeH+ZczjS5+hfUYXRiYMfPQyo+k9VPX693H5ImwzZ6JIApQJlpGSdhHIGDw+Bz2QCEzRi5yvi4VDwy5HorUHblAcrZxvN5afFx9AO3w6IeEuoVxEzibB9Qm26IBnj4RJ8syAXJDWqdZ9J4X1Hp5ePV37+fPVXwzN+Lrdu7fy5AZCmQU6JaQ80ualnjwzeKSuHKFYNO3GIKOSDFh7mPEg97NYSMFk6B3Nsr9+trs4ADBjTJHQUrNfj6fzw5Gl3vwFQM=
  file: build/libs/xlr-qtest-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    repo: xebialabs-community/xlr-qtest-plugin
