language: java
notifications:
  hipchat:
    rooms:
      secure: CD77cohawdMYwZXvL6b8At0d43fSYW5/9K17UjJsKz2LR2Wf2GZiYDiCGydxq4KQ/S4dKzSB7yfac4MXrzKdwiDnQYokfiHqMr6qtvzqXXpCEViz6dImOR4yYbrp3VfaY6nXgYYjMaF5dQ6Wsca42zgnpd3ZNi8/Ylo2x4gsUhGKtqidGnCVmo3NB1J6QHJk6cRvsQmy9p2ZroSrLpQWAGRN3OyiiduoKvCPrhk5OTwuuJbhR4ECwtOfWnBRtpMTWauOex7z7Qn2vLQbZ+DIspQxjoA1Pb6Qm4TGG8G1DBWb9rDjFjDV4DhBI/dTpS1Ov7cRNLiop1aFtQEbkwcAurypCAlkvqvUpU444VUMhmaAWFXTqOKWKDVbBR0DogsLW6wE43QhHpNByahb6vUOfpdqfcAWoDCaoPbR7RmrP34XMYVnb/PIFg8h1H4HNEqTF4ixFPqcWhUfMZW2ADjIIHGI25/Ylt68GA50On4/oXdNp1wE+qsR/nJKGT8EM2BhYolXDoPJtMsDdxWaAnoGR9evOEAXUsH6PMfCIYjOk78kVyRsUt2evIdrUK8MFe8yYy9T53Wq+YFfIGeTVqXEMhAiDzzb9jU55ixjDMgl0ITLX03VjpPtxGLWd31e05+KA9AP47P2Bv/cQsCluWxHqWZ1MRfogo7tz1v5qqOHrDQ=
deploy:
  provider: releases
  api_key:
    secure: LiAHufqUbsV6Qv0XWwiDx90wDXsbf4+36I349/wx91d2hSZBgkaqPgDdLwLXPIP9ViXOx/agkV/C9Dmm3jPQSSczCwlFGoKfrWLKyEnOrVDnZnNa/EtZi+odAplfBO4sB+m9KAng0X5NWU+qeXB4mFD5+uI9gi5GJfhDoAcpu7yVKJt6Ukyf/ars3P52bfCqVN0ockwC3GcUCsJM5uFM71TPmFK5G4ir+C7Z3GEtAezJqCuNitnK6e0PMIwdnnH0cEV2xNyjKV5ikPs8/GgI/oXKSSVWQAoL+948XSeUNqBQNInrXA/6anskN07+4QIW65WL5KA3dLyZzkerhi1SD/W5AVl/2BupYu/sw8zEH0ffyLK6Tq5SIb34N4MtVy805FslYpnMGYH+1rZDq2vBMmGK3mhCxyuyLaC5eLfc7KeH+ZczjS5+hfUYXRiYMfPQyo+k9VPX693H5ImwzZ6JIApQJlpGSdhHIGDw+Bz2QCEzRi5yvi4VDwy5HorUHblAcrZxvN5afFx9AO3w6IeEuoVxEzibB9Qm26IBnj4RJ8syAXJDWqdZ9J4X1Hp5ePV37+fPVXwzN+Lrdu7fy5AZCmQU6JaQ80ualnjwzeKSuHKFYNO3GIKOSDFh7mPEg97NYSMFk6B3Nsr9+trs4ADBjTJHQUrNfj6fzw5Gl3vwFQM=
  file: build/libs/xlr-qtest-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    repo: xebialabs-community/xlr-qtest-plugin
