language: java
notifications:
  hipchat:
    rooms:
      secure: Y8cTB7lDGlcahj8fV4L76YMABZIkucOhR4IQNY3ECXvihGc2SXEqOg2b0AWmqv39OuoGg9LfJXFYzlkSdEw0HNPzMd+sdc1tSmCqG3jmizg1fXAqLjZc5Da1X3v0Cycb3UiGSp2nizd9b0DaGYvsio9ELJDzttOvQNIWaTjeMesfc+LNz5i81zBd0nreH9dJcCgEC1MvuE1Z77Dmx1nqWNK/sfoP/yqq6DJbHQRgSr4Pfv0SAbzByBg0hWz7O/0JACJNm6+khjXbxCc5wKCCLbx7xA7W9s+nDJGkTKj+vKRzpPcWo6DhjdD41b788M5/35/nRnR7kiOpjn9dFSAisBRgsdwPODEuzCkzmwICMRQE6POStVkTCEW4AKMEGYN0mJ0yab1exHk2jkSMck2cOV35J/sZWZ+oeQgkhABkcJtzuYIAFjVLB5RHgPO04KeSGrpP8w9gRBh5f/ooOOyeqh3WEGnboiYN8hZQhJcf25wC/7gAnUlnXJEWvOV1KDWMahny2mFFcGL26MkRr86ECu8Yz7wEWRcIc+FRx/58LrYQP4LDSpGUB+VFrOnVxIRn2QNWn6W+t1XZ/7Kz7aLnUDRA0p9/3GZHTHy0As6chCq9HAD92JuS6icjrEzUH/uylULjUKAM632j9oAGwUf6W0s1lhuBUuXrXdBjg8SSBR4=
deploy:
  provider: releases
  api_key:
    secure: iNDRtQ9F95+3c8+znu2UF1FK7LPM4LI+VWmJR4XTl+fND20lchf9qkdD3C2zL0+RLOYt8sKrykcVkebDx+z6j2rNvCj8ZTYiHrgn2xPilTHZUOSqAHc/Kqx+LgewTka1x8qx7VYGAoChUvU0t61VRy/izjGGMkQhKWq2zj3mu+JhiJo753mK3faiA2/593LnrlvnbQy44fG7oZVxRwPQxdiqoUGY+Pz3EMYxZFGm8q1s7Aiv3JAxbwqenJKOMMTYRGtmRaYIFOHxow2PJAfk6wZsgVX1jqJmmQ5G/43h9eaWJg+E+XYb4erfbD8cHQJ0BKZmK6x6TcWKLK5jNLAYeRpJk8l05nzkfEEWjiABF9oLDS7wGhWC/EzfMIlCLtu5W0dpGta0AOAFRQNiS0UDfOEh/o8a3HmA4IQqNH9woaMbqnKS1r+dHVk18042r9Ne+eU7PdrUIEM9+AjJRLCvrZrvb/Lp6hLM6bkiDxwhhnR0iz6wN2Xc5k0h406U2zVlDrvsMSWFdgdKjSEO/gnYwANsnCNN1gaN2oNlS+JFg9v931ccN1rpKsE3fdD/MtkkT2WGINoMAX0NwdFnh2C8yILv+lpgRcmRTlio412BNrBJTZofazdeSN+hJqlO+aMoBGZTGvN+dLhjHmsYBBiiMvvqZZIaHPfH43g9Z9atKEA=
  file: build/libs/xlr-qtest-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-qtest-plugin
