language: java
notifications:
  hipchat:
    rooms:
      secure: ZiSyGwuy09O35VDhaUUtAIg3Feqx1vcmustxIEGL32+W6Dbw/UjhLWXsQofgPN0EFXcwpe9R7IyolYECQGBPrh75ftgnRZ7NOYdli3bdcudhLFLeiOvtP57274BWx+rMAOA8sk4CDvV/keToqxJlZ2RLSBoWGK/qwjtu0oP/jizuZ1BiFvOSppW7pj189lCidJdoRwpnr2/Ee4j9A0iTSmWRztriwMvfvL1Euyr8PP8xVKgypKKXtOT9kcl22k8T9dl35ps/D/FK/qhGXJEFjpSo2a1XniaQiw5zNr1m4ACrt7lChyHeKZYRHZD7A706OxAdkgzch33OcIi5IFpH7QtEDGUhWclaA7j3D48w9cJ8SP5RNOoxQ/kKso7Q9EQ+6Ism6rGr6R62KWUbCTM2/+cntOVJ97nzL9GOLOOt+YFLbBjLyPMEdj0xrw+CSVtmfNzJ6rT6MeXbhwSvRm3mB31mDHBE0fmMdHvr6ZEo76b169QSfdR6C4Di5dENrsMzobiL83T6pPksHweTdoTFfyx3Wk9rkp2iwWrb8saZOKm9H9ZwFLRhNbU3stj6LVjtZJArf3aAwLFlIqgGWnDL2HH7O01lXFXtZyJ+licNMWasOyCV4uP75ZHMIA6/v9V5UNCUNTdhE7vHRJbWmXQz+WNb+OlNqQcv0mc3nFADXkQ=
    on_success: always
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: eI2FTYaWJjtvZximjYMsVzpj48mi2NEB2QyANpOzD/T+6MBfoQpAqg1KLjjqZydt3B+9nN79hapzRfeocbiVIlynsLM1dNXHuLC91yNW+4j1hXIJyPd8q1GqvVspEIO19Oit5GvPTxu3s5XlGjByizZuii8zLgmSRJb+nVqnD+llHFpiFMDtVT/QFTeqIypXX0te051UHtdAjGraPgYjs5OhEFPB8v1rg5nrVyj/Tbop7t2lL6Hg0r/PNlM9tIFEelX6tcrD1MTnnPUIvq1s7jIC1cm8OKgroL7sEE2C57q6N64jRwnl2qFy3xEys9QuI+R+B5V1wU9HHsGcqMkxu1dBARsKS1vN3YZ/YFDz7uFhe+CchnUNCSAIYTKxoKTTE9bsaJ3a/G4n0D1hYiKccK0rqaAs5QqsRJ34i+DnMFJcQzMPSc43JlUfQ0Up5qIYHtD4/WnP9Be7+upKKOlIROdfBBKWX2Z1FG08QL/y8TVCez9tq2dHYvC0tleFwpDf25T/Tcp5AxBDDUkF1+vzVWuRzpAn9t6FEBaKEK4pOzZI72nGR6m+1rv7PB6PA1bQlhARN5AdA8pcepXYh1oWuLPd7gQOcVLsEAK70vrGBMFsSCcKp/zSjCTGRcAoDvxEps7ZIkduf0qXQ8XP2mRFLY6pFJ56cHM2vBPvCcG4mZg=
  file: build/libs/xlr-qtest-plugin-1.1.1.jar
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: xebialabs-community/xlr-qtest-plugin
